kafka:
  consumer:
    consumers-container:
      - container-name: create-person
        bootstrap-servers: localhost:9092
        group-id: groupId
        concurrency: 3
        auto-offset-reset: latest
        max-poll-records: 500
        max-poll-interval: 60000
      - container-name: create-person-retry
        bootstrap-servers: localhost:9092
        group-id: groupId
        concurrency: 3
        auto-offset-reset: latest
        max-poll-records: 500
        max-poll-interval: 60000