kafka:
  producer:
    topic-producers:
      - topic-prefix: create-person
        bootstrap-servers: localhost:9092
        ack: all
      - topic-prefix: create-person-retry
        bootstrap-servers: localhost:9092
        ack: all