kafka:
  producer:
    topic-producers:
      create-person:
        bootstrap-servers: localhost:9092
        ack: all
  consumer:
    consumers-container:
      person:
        bootstrap-servers: localhost:9092
        group-id: groupId
        concurrency: 3
        auto-offset-reset: latest
        max-poll-records: 500

person:
  create-topic: create-person