kafka:
  producer:
    topic-producers:
      - topic-prefix: create-person
        bootstrap-servers: localhost:9092
        ack: all
      - topic-prefix: create-person-retry
        bootstrap-servers: localhost:9092
        ack: all
  consumer:
    consumers-container:
      - container-name: create-person
        bootstrap-servers: localhost:9092
        group-id: groupId
        concurrency: 3
        auto-offset-reset: latest
        max-poll-records: 500
      - container-name: create-person-retry
        bootstrap-servers: localhost:9092
        group-id: groupId
        concurrency: 3
        auto-offset-reset: latest
        max-poll-records: 500

person:
  create-topic: create-person
  create-topic-retry: create-person-retry